### ISSUE TITLE
Select width when set on element or via ID

### ISSUE THREAD

**Issue by martyf** [AudithSoftworks/Uniform#342]
The width of the select element is miscalculated when setting the width of a select box via:
- "style" attribute on the <select> itself
- container or select using ID (and #myClassName)

The impact of this is that the right side of the button is not clickable.

If you set the width of the select using a class, the select behaves as normal.

![width](https://f.cloud.github.com/assets/1491079/700780/eae832ce-dd5a-11e2-9258-ea88e41b104a.jpg)

This illustrates Firebug's Inspect Element, looking at the width - when set via class, the width is correct. When set via ID, the width is incorrect.

Here is an example with a custom theme - given the bigger width of the Select element (compared to the Default theme), the issue is more prominent:
![image](https://f.cloud.github.com/assets/1491079/700817/457dcb48-dd5d-11e2-9145-344d0670cb18.png)

I am assuming it is to do with the priority given to an ID (and direct attributes) over a class when rendering the styles, and not sure if there's a workaround within UniformJS to force a resolution for this - or perhaps needs noting in the documentation if this is expected and unchangeable behaviour.

Here is the source code of select.html, based on demo.html, which illustrates the issue:
https://gist.github.com/martyf/5856228

**Comment by shehi** [comment]
Reproduced and confirmed:

https://jsfiddle.net/Shehi/w52k7yL1/

**Comment by shehi** [comment]
I believe this issue is related to Specificity concept in CSS. Uniform successfully applies styles (which naturally come from external CSS assets), but if you have higher Specificity styles overriding Uniforms relatively lower ones, such as: inline or id-based styles, then this very issue will arise.

As this is due to the architecture of CSS, I don't think acting against it, or inventing some workaround (such as adding `!important` to styles) would be a good coding practice. I recommend you calculate the Specificity of your CSS and make sure some unexpected override doesn't ruin desired results.

More on the topic of [Specificity, Inheritance and Cascade in CSS](http://vanseodesign.com/css/css-specificity-inheritance-cascaade/).
