### ISSUE TITLE
Form reset doesn't affect checkboxes, radios, selects - but only inputs.

### ISSUE THREAD

**Issue by pratiksha2211** [AudithSoftworks/Uniform#348]
Uniform reset does not allow to reset checkbox on form reset button .. 

Thanks

**Comment by shehi** [comment]
Uniform generally doesn't handle any form mechanisms, including "Reset" buttons, but rather provides options to help with their handling.

For proper Reset button handling you could `update()` them:

```
$("input[type='reset']").click(function(e) {
    setTimeout(function () {
        $uniformed.uniform.update();
    }, 1);
});
```

`setTimeout()` function here is required for a potential race-condition: Uniform needs to wait at least a millisecond for native reset event kick in and finish, so that it could `update()` with reset values.
