### ISSUE TITLE
display: block on .active class breaks click in Firefox

### ISSUE THREAD

**Issue by hadl** [AudithSoftworks/Uniform#395]
Happens in FF 27.0.1.
Check this fiddle: http://jsfiddle.net/7bVN3/

**Comment by shehi** [comment]
Verified: http://jsfiddle.net/Shehi/jxgn4Loz/

**Comment by shehi** [comment]
I couldn't find the underlying cause for this behavior, so might need an extra set of eyes for this one.

EDIT: After working on #342, I think the logic of these two issues are somehow related. More to come soon.

**Comment by shehi** [comment]
When I added `display:none` to Uniform's external style files, this behavior didn't show up (you can easily test that by just downloading the package, editing SCSS files, compiling them and checking the result in demo pages provided). But when you add relatively _higher_ Specificity rule (such as inline CSS, or id-based one), that rule overrides Uniform ones. To some extent, this issue is related to #342 - in both cases, higher Specificity rule damages things. I strongly recommend you guys make sure all your CSS assets are designed with Specificity of CSS rules taken into account. I don't plan adding dirty overrides (such as `!important` to code). Closing this one under the same premise I closed #342.
