### ISSUE TITLE
Unified Select Dropdown Menus happens to bug

### ISSUE THREAD

**Issue by tchauviere** [AudithSoftworks/Uniform#406]
Hi !

First thanks for this very nice and usefull plugin !

I found out a bug that happens on some browsers and mainly on default android browser of Samsung's smartphones. On these ones, a "unified select dropdown menu" will open a layout with available options like it should, but this layout will close instantly, so it's impossible for the user to select the option he wants.

I tried to figure out what could be the origin of this issue with no luck so I decided to open an issue here.

Here is a website where I could reproduce this issue :
http://fo.demo.prestashop.com/en/contact-us (on subject heading's dropdown)

Thanks for your help !

Best regards,

**Comment by vmulot** [comment]
did you resolve your pb ? i have the same...
thanks :)

**Comment by artshipulin** [comment]
This is caused by PrestaShop's use of jQuery Uniform, not by Uniform itself. When viewport resizes PS calls ```$.uniform.update("select.form-control, input[type='file']");```. That forces Uniform to rebuild select controls if `options.selectAutoWidth == true`, which is the default. Some DOM modifications that happen when Uniform controls are rebuilt cause the select to lose focus and close. 

This issue is not unique to Samsung's stock browser, but rather any mobile browser that shows select options in the bottom half of the screen instead of showing a list that covers the viewport. 

![screenshot_2015-08-26-06-04-23](https://cloud.githubusercontent.com/assets/7014137/9492051/998e0b2c-4bb9-11e5-8272-8171bfddb917.png) ![screenshot_2015-08-26-06-07-28](https://cloud.githubusercontent.com/assets/7014137/9492052/998e7e5e-4bb9-11e5-9cd2-76da42353626.png)

Depending on your PrestaShop theme you can fix it by either setting `selectAutoWidth` to `false` or adding a condition to call `$.uniform.update(...)` only on viewport width changes, but not height. With some themes it might be OK to remove on resize call to `$.uniform.update(...)` completely.
