### ISSUE TITLE
Add error state to form elements

### ISSUE THREAD

**Issue by pixelmatrix** [AudithSoftworks/Uniform#9]
Got a suggestion to add an error state for when there are errors in the form.

**Comment by shehi** [comment]
This can be easily done by just creating your own sprite based on that of Uniform's and add additional classes to your own CSS and also handle them in your own JS. Adding a class, let's say `class='error'` should use the newly added sprite sections with newly added CSS bits and be handled by your own JS code. I don't see why this package should extend its responsibilities this far. Otherwise, we also have a request to add JS-based animation handling for form elements: #116. Expanding this far will only degrade Uniform's performance further. 

I am binning this feature for the moment and tagging it as "for future reconsideration".
